version: 2
jobs:
  build:
    machine: true
#         working_directory: ~/projects
    steps:
      - checkout
      - run: mvn clean package
  dependencies:
    machine: true
    steps:
      - checkout
      - run: mvn  clean install dependency:resolve-plugins dependency:go-offline

#  test:
#    machine: true
#    steps:
#      - checkout
#      - run:  mvn -o surefire:test

  deployment:
    machine: true
    steps:
      - checkout
      - run: |
           mvn -s .circleci.settings.xml  deploy
           mvn -Pwaisely clean deploy


workflows:
  version: 2
  workflow:
    jobs:
    - build
    - dependencies:
        requires:
          - build

#    - test:
#        requires:
#          - build
    - deployment:
        requires:
          - dependencies
#          - test