version: 2
jobs:
  build:
    machine: true
#         working_directory: ~/projects
    steps:
      - checkout
      - run: mvn clean package
  dependencies:
    machine: true
    steps:
      - checkout
      - run:
          override:
            - mvn  clean install dependency:resolve-plugins dependency:go-offline

  test:
    machine: true
    steps:
      - checkout
      - run:
          override:
            - mvn -o surefire:test

  deployment:
    machine: true
    steps:
      - checkout
      - run:
          main:
          commands:
                - mvn -s .circleci.settings.xml  deploy
                - mvn -Pwaisely clean deploy
#      - run: cd ..
#      - run: git clone https://github.com/MartinTopchyan/circleci-demo.git
#      - run: cd circleci-demo
#      - run: mvn package