version: 2
jobs:
  build:
    working_directory: ~/circleci-lib-demo
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - restore_cache:
          key: spreading-lib-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
          - ~/.m2
          key: spreading-lib-{{ checksum "pom.xml" }}

      - run: mvn clean package -DskipTests
  test:
    working_directory: ~/circleci-lib-demo

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: mvn clean  install

#  test:
#    machine: true
#    steps:
#      - checkout
#      - run:  mvn -o surefire:test

  deployment:
    working_directory: ~/circleci-lib-demo
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: apt-get -y -qq install awscli
#      - run: |
#           mvn -Pwaisely -s .circleci/settings.xml clean deploy -DskipTests

      - run: mvn  clean deploy -DaltDeploymentRepository=repo.com.waisely::default::s3://repo.com.waisely/snapshot


workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build
#    - test:
#        requires:
#          - build
    - deployment:
        requires:
          - test
#          - test