version: 2
jobs:
  build:
    working_directory: ~/circleci-lib-demo
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - restore_cache:
                key: spreading-lib-{{ checksum "pom.xml" }}

            - run: mvn dependency:go-offline

            - save_cache:
                paths:
                - ~/.m2
                key: spreading-lib-{{ checksum "pom.xml" }}

      - run: mvn clean package -DskipTests
  test:
    working_directory: ~/circleci-lib-demo

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: mvn clean  install

#  test:
#    machine: true
#    steps:
#      - checkout
#      - run:  mvn -o surefire:test

  deployment:
    working_directory: ~/circleci-lib-demo
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: |
           mvn -s .circleci/settings.xml  deploy
           mvn -Pwaisely clean deploy


workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build
#    - test:
#        requires:
#          - build
    - deployment:
        requires:
          - dependencies
#          - test