version: 2
jobs:
  build:
    machine: true
#         working_directory: ~/projects
  dependencies:
    machine: true
    steps:
      override:
        - checkout
        - mvn  clean install dependency:resolve-plugins dependency:go-offline

  test:
    machine: true
    steps:
      override:
        - checkout
        - mvn -o surefire:test

  deployment:
    machine: true
    steps:
      main:
        commands:
          - checkout
          - mvn -s .circleci.settings.xml  deploy
          - mvn -Pwaisely clean deploy
#      - run: cd ..
#      - run: git clone https://github.com/MartinTopchyan/circleci-demo.git
#      - run: cd circleci-demo
#      - run: mvn package